### ISSUE TITLE
Let them speak!

### ISSUE THREAD

**Issue by timber-they** [marvinborner/HG2G-404#1]
The sperm whale, just as well as the petunias actually speak. I'm aware that it might be tricky to implement the whole monologue of the sperm whale, but at least the iconic 

> Oh no, not again.

of the petunias could be included (via a speech bubble or actual sound effects).

Just for the case that the thoughts of the sperm whale will actually get included as well, here they are:

> Ah … ! What’s happening?
Er, excuse me, who am I?
Hello?
Why am I here? What’s my purpose in life?
What do I mean by who am I?
Calm down, get a grip now … oh! this is an interesting sensation, what is it? It’s a sort of … yawning, tingling sensation in my … my … well I suppose I’d better start finding names for things if I want to make any headway in what for the sake of what I shall call an argument I shall call the world, so let’s call it my stomach.
Good. Ooooh, it’s getting quite strong. And hey, what’s about this whistling roaring sound going past what I’m suddenly going to call my head? Perhaps I can call that … wind! Is that a good name? It’ll do … perhaps I can find a better name for it later when I’ve found out what it’s for. It must be something very important because there certainly seems to be a hell of a lot of it. Hey! What’s this thing? This … let’s call it a tail – yeah, tail. Hey! I can can really thrash it about pretty good can’t I? Wow! Wow! That feels great! Doesn’t seem to achieve very much but I’ll probably find out what it’s for later on. Now – have I built up any coherent picture of things yet?
No.
Never mind, hey, this is really exciting, so much to find out about, so much to look forward to, I’m quite dizzy with anticipation …
Or is it the wind?
There really is a lot of that now isn’t it?
And wow! Hey! What’s this thing suddenly coming towards me very fast? Very very fast. So big and flat and round, it needs a big wide sounding name like … ow … ound … round … ground! That’s it! That’s a good name – ground!
I wonder if it will be friends with me?

[Source](https://www.goodreads.com/quotes/198068-another-thing-that-got-forgotten-was-the-fact-that-against)

**Comment by marvinborner** [comment]
Great idea. Actually these monologues have already been implemented in  c34c318 - but they're currently only logged to the console. I'll implement the talking ASAP.
